#!/usr/bin/env bash
#configures a new Ubuntu machine to respect below requirements
#Install nginx on your web-01
#Nginx should be listening on port 80
#When querying Nginx at its root using curl, return a page Hello World!

apt update
apt -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
