#!/usr/bin/env bash
#configures a new Ubuntu machine to Install nginx

apt update
apt -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
