#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get -y install nginx
echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/sites-available/default
sudo service nginx restart
