#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

apt-get install --no-install-recommends -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get install -y haproxy=2.0.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 399810-web-01 54.152.133.243:80 check
   server 399810-web-02 54.237.34.128:80 check
" >> /etc/haproxy/haproxy.cfg

service harproxy start
