#!/usr/bin/env bash
#a Bash script that loops from 1 to 10

index=1
while [ $index -le 10 ]
do
	if [ $index -eq 4 ]
	then
		echo "bad luck"
	elif [ $index -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((index++))
done
