#!/usr/bin/env bash
# make your fix short and sweet.
apt-get install -y nginx
service nginx stop
sed -i 's/^user .*;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/^listen .*;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx start
